### ISSUE TITLE
erreur d'installation

### ISSUE THREAD

**Issue by Francky78G** [ErnadoO/mondial-relay-bundle#1]
Bonjour, lorsque j'essaie d installé ErnadoO/mondial-relay-bundle j'ai ce message d'erreur qui intervient

je precise que 
 j 'ai bien fait l installation de : composer require quentinbontemps/php-mondialrelay-api
puis lorsque je fait : composer require ernadoo/mondial-relay-bundle

voici mon message d'erreur
![error](https://user-images.githubusercontent.com/83401765/125439142-f4c0c379-eb3a-49a1-8823-5aaecc2c955d.png)

merci

**Comment by ErnadoO** [comment]
Hello @Francky78G

- L'installation manuelle de la lib quentinbontemps/php-mondialrelay-api n'est pas nécessaire puisque c'est une dépendance de ce bundle, elle sera automatiquement installée.
- Pour l'erreur elle même, en effet je n'ai pas publié les recipes sur symfony/recipes-contrib du coup il te faut créer le fichier de config manuellement (https://github.com/ErnadoO/mondial-relay-bundle#step-3-configure-the-bundle) et ensuite faire ton composer req ernadoo/mondial-relay-bundle

**Comment by gregcozy** [comment]
Bonjour, il y a un fichier mondialrelay.html.twig celui-ci permet il d'afficher quelque chose et si oui comment faire s'il vous plait?

**Comment by ErnadoO** [comment]
Bonjour

Ce fichier est utilisé par la debug toolbar et le profiler, rien de plus
